project_id = "rwvlvooojegpebognnzn"

[functions.migrate-contentful-hero]
verify_jwt = false

[functions.send-contact-email-ses]
verify_jwt = false

[functions.send-support-request]

[functions.get-contentful-config]

[functions.translate-content]
verify_jwt = false

[functions.ses-selftest]
verify_jwt = false

[functions.customer-auth]
verify_jwt = false
