// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyxlqcavscrthjkonght.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5eGxxY2F2c2NydGhqa29uZ2h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MDI3MjEsImV4cCI6MjA1OTM3ODcyMX0.yg5kCaG6KvCqC-MvoKxTduEXPW6ZJrrn7PUcS_RMOBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);