// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwvlvooojegpebognnzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3dmx2b29vamVncGVib2dubnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1Njg1ODcsImV4cCI6MjA2MjE0NDU4N30.a_sN-wS6z6EwaFxNdDwprjAyWamti8TPs3ODIps_4ZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);